### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by kristianmandrup** [breuleux/inquirer-promise#1]
Inquirer is now at `^1.2.1`

**Comment by breuleux** [comment]
Done, although that required a rewrite. Good news is that I removed the other dependency.

**Comment by kristianmandrup** [comment]
Cool :)

**Comment by kristianmandrup** [comment]
Perhaps you should rename it to `inquirer-ext` or something more fun like: `sexy-questions` or `inquisitorz` ;)

**Comment by breuleux** [comment]
I think I'm going to go for `inquirer-shortcuts`, because I'm no fun ;) (also it should have `inquirer` in the name)
